OpenTIE:
  description: "OpenTIE is an open-source reimplementation of Star Wars: TIE Fighter."
  release_names:
    stable: opentie
    edge: opentie-edge
  scm:
    url: elyosh/OpenTIE
OpenXWA:
  description: "OpenXWA is an open-source reimplementation of the 1999 game Star Wars: X-Wing Alliance."
  release_names:
    stable: openxwa
    edge: openxwa-edge
  scm:
    url: elyosh/OpenXWA
OpenXvT:
  description: "OpenXvT is an open-source reimplementation of the 1997 game Star Wars: X-Wing vs. TIE Fighter with its Balance of Power expansion."
  release_names:
    stable: openxvt
    edge: openxvt-edge
  scm:
    url: elyosh/OpenXvT
