OpenTIE:
  slug: opentie
  appstream_id: io.github.elyosh.OpenTIE
  summary: "A reimplementation of Star Wars: TIE Fighter."
  description: "OpenTIE is an open-source reimplementation of Star Wars: TIE Fighter."
  scm:
    url: elyosh/OpenTIE
OpenXWA:
  slug: openxwa
  appstream_id: io.github.elyosh.OpenXWA
  summary: "A reimplementation of Star Wars: X-Wing Alliance."
  description: "OpenXWA is an open-source reimplementation of the 1999 game Star Wars: X-Wing Alliance."
  scm:
    url: elyosh/OpenXWA
OpenXvT:
  slug: openxvt
  appstream_id: io.github.elyosh.OpenXvT
  summary: "A reimplementation of Star Wars: X-Wing vs. TIE Fighter."
  description: "OpenXvT is an open-source reimplementation of the 1997 game Star Wars: X-Wing vs. TIE Fighter with its Balance of Power expansion."
  scm:
    url: elyosh/OpenXvT
OpenXW:
  slug: openxw
  appstream_id: io.github.elyosh.OpenXW
  summary: "A reimplementation of Star Wars: X-Wing."
  description: "OpenXW is an open-source reimplementation of the 1993 game Star Wars: X-Wing."
  scm:
    url: elyosh/OpenXW
