OpenTie:
  description: "OpenTIE is an open-source reimplementation of Star Wars: TIE Fighter."
  release_names:
    release: opentie-release
    main: opentie-main
  scm:
    url: elyosh/OpenTIE
OpenXWA:
  description: "OpenXWA is an open-source reimplementation of the 1999 game Star Wars: X-Wing Alliance."
  release_names:
    release: openxwa-release
    main: openxwa-main
  scm:
    url: elyosh/OpenXWA
OpenXvT:
  description: "OpenXvT is an open-source reimplementation of the 1997 game Star Wars: X-Wing vs. TIE Fighter with its Balance of Power expansion."
  release_names:
    release: openxvt-release
    main: openxvt-main
  scm:
    url: elyosh/OpenXvT
