name: Build AppImages

on:
  workflow_dispatch:
  push:
    paths:
      - resources/meta.yml
      - ci/read_releases.py
      - ci/package_appimage.sh
      - ci/publish_release.sh
      - .github/workflows/cicd.yml
      - .github/workflows/linux-x86_64-cicd.yml

permissions:
  contents: write

jobs:
  linux-x86_64:
    uses: ./.github/workflows/linux-x86_64-cicd.yml
    secrets: inherit